services:
  mysql:
    build:
       context: .
       dockerfile: config/mysql/Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./storage/mysql/:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 700M
    ports:
      - "${MY_ADMIN_PORT}:80"
    depends_on:
      - mysql
  php:
    build:
      context: .
      dockerfile: config/php/Dockerfile
    volumes:
      - ./:/usr/src/myapp
    depends_on:
      - mysql